#!/usr/bin/env bash
set -eu
cd "$(dirname "${BASH_SOURCE[0]}")"

php -d include_path="$PWD"/src/php -f src/php/generate.php -- "$@"
if [[ $# -ne 0 ]]; then exit; fi

echo -n 'tsc... '
tsc
echo ok
mkdir -p docs/js/lib
cp src/ts/lib/*.js docs/js/lib